(require 'prof)
(defconst prof-default-c-style
  `("gnu"
    (indent-tabs-mode . nil)
    (c-basic-offset . 2)
    (c-offsets-alist .
                     ((substatement-open . 0)
                      (access-label . /)
                      (case-label . +)))))
(defun prof-default-oninit ()
  (c-add-style "default" prof-default-c-style))
(defun prof-default-onfini ()
  t)
(defun prof-default-c-mode-common-hook ()
  (c-set-style "default"))
(defun prof-default-sh-mode-hook ()
  (setq sh-basic-offset 2))
(defun prof-default-python-mode-hook ()
  (setq python-indent 2))
(defun prof-default-nxml-mode-hook ()
  (setq nxml-child-indent 2))
(defun prof-default-vhdl-mode-hook ()
  ;(vhdl-set-style "IEEE")
  (setq vhdl-basic-offset 4)
  (setq vhdl-child-indent 4)
  (setq vhdl-electric-mode nil))
(defconst prof-default
  `("default"
    (initfn . prof-default-oninit)
    (finifn . prof-default-onfini)
    (hooks . ((c-mode-common-hook . prof-default-c-mode-common-hook)
              (sh-mode-hook       . prof-default-sh-mode-hook)
              (python-mode-hook   . prof-default-python-mode-hook)
              (nxml-mode-hook     . prof-default-nxml-mode-hook)
              (vhdl-mode-hook     . prof-default-vhdl-mode-hook)
              ))))
(profs-add prof-default)
(provide 'prof-default)
